spring:
  datasource:
    url: jdbc:postgresql://localhost:6666/postgres
    username: root
    password: toor
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
  grpc:

server:
  port: 8081